services:
  golangapi:
    build:
      context: golangAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      GROQ_KEY: ${GROQ_KEY}

  pythonapi:
    build:
      context: pythonAPI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always